# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'PlenR' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PlenR
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'

  target 'PlenRTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
